# Generated by Django 3.2.4 on 2021-06-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
    ]
